title: RaspBella's blog
email: bella.campbell@tuta.io
description: >- # this means to ignore newlines until "url:"
  A place to yap about;
  Rubik's cubes,
  Trains,
  and Computer Science
url: "https://blog.raspbella.xyz"
twitter_username: RaspBellamy
github_username:  RaspBella

# Build settings
theme: minima
plugins:
  - jekyll-feed
